version: '3'
services:
  api:
    image: uod-occupancy-tracker-api
    restart: always
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

  web-cli:
    image: uod-occupancy-tracker-api
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
