version: '3'
services:
  api:
    build: ./api/
    restart: always
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/usr/src/app
      - /usr/src/app/node_modules
    container_name: uod-lib-occupancy-api

  web-cli:
    image: uod-occupancy-tracker-api
    networks:
      - backend
    command: sh
    container_name: web-cli-container

  total-occupancy:
    build: ./total-library-occupancy
    restart: always
    # depends_on:
    #   - api
    networks:
      - backend
    container_name: uod-lib-total-occupancy

  mysql:
    image: mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=u0Dl1brary_
      - MYSQL_DATABASE=uodLibraryOccupancy
    volumes:
      - occupancy-tracker-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306" # remove this for prod
    container_name: uod-lib-occupancy-mysql

networks:
  backend:
    driver: bridge

volumes:
  occupancy-tracker-mysql-data:
    external: true
