version: "3"
services:
  api:
    build: ./api/
    restart: always
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./api/src:/usr/src/app
      - /usr/src/app/node_modules
    container_name: uod-lib-occupancy-api

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - api
    networks:
      - backend
    volumes:
      - /etc/letsencrypt/live/uod.davidtopping.dev/fullchain.pem:/etc/ssl/cert.pem
      - /etc/letsencrypt/live/uod.davidtopping.dev/privkey.pem:/etc/ssl/privkey.pem
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: uod-lib-occupancy-nginx

  library-occupancy-calculations:
    build: ./library-occupancy-calculations
    restart: always
    networks:
      - backend
    container_name: uod-lib-occupancy-calcs
    volumes:
      - ./library-occupancy-calculations:/usr/src/app

  mysql:
    image: mysql
    networks:
      - backend
    environment:
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=u0Dl1brary_
      - MYSQL_DATABASE=uodLibraryOccupancy
    volumes:
      - occupancy-tracker-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    container_name: uod-lib-occupancy-mysql

networks:
  backend:
    driver: bridge

volumes:
  occupancy-tracker-mysql-data:
    external: true
