version: '3'
services:
  api:
    image: uod-occupancy-tracker-api
    restart: always
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    container_name: uod-lib-occupancy-api

  web-cli:
    image: uod-occupancy-tracker-api
    networks:
      - backend
    command: sh
    container_name: web-cli-container

  mysql:
    image: mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=u0Dl1brary_
      - MYSQL_DATABASE=uodLibraryOccupancy
    volumes:
      - occupancy-tracker-mysql-data:/var/lib/mysql
    ports:
      # remove this for prod
      - "3307:3306"
    container_name: uod-lib-occupancy-mysql

networks:
  backend:
    driver: bridge

volumes:
  occupancy-tracker-mysql-data:
    external: true
